# Step 1: Import Cleaned Dataset into SQLite

### Objective
Import the cleaned Superstore dataset into a SQLite database named **superstore.db**. The imported table will be used to perform SQL queries for data extraction and analysis.

In [52]:
import pandas as pd
import sqlite3

In [53]:
# Load the cleaned dataset

df = pd.read_csv("../data/cleaned_superstore.csv")

# Display first five rows
df.head()

,csvbase_row_id,﻿Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,3,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
2,5,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
3,6,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
4,7,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656

In [54]:
# Connect to SQLite Database

conn = sqlite3.connect("../database/superstore.db")

print("Connected Successfully!")

Connected Successfully!

In [55]:
# Import dataset into SQLite

df.to_sql(
    "superstore_data",
    conn,
    if_exists="replace",
    index=False
)

print("Dataset Imported Successfully!")

Dataset Imported Successfully!

In [56]:
# Check table names

query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, conn)

              name
0  superstore_data

In [57]:
# Display first five records

query = """
SELECT *
FROM superstore_data
LIMIT 5;
"""

pd.read_sql(query, conn)

,csvbase_row_id,﻿Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,3,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
2,5,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
3,6,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
4,7,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656

In [58]:
# Check column names

query = """
PRAGMA table_info(superstore_data);
"""

pd.read_sql(query, conn)

    cid            name     type  notnull dflt_value  pk
0     0  csvbase_row_id  INTEGER        0       None   0
1     1         ﻿Row ID  INTEGER        0       None   0
2     2        Order ID     TEXT        0       None   0
3     3      Order Date     TEXT        0       None   0
4     4       Ship Date     TEXT        0       None   0
5     5       Ship Mode     TEXT        0       None   0
6     6     Customer ID     TEXT        0       None   0
7     7   Customer Name     TEXT        0       None   0
8     8         Segment     TEXT        0       None   0
9     9         Country     TEXT        0       None   0
10   10            City     TEXT        0       None   0
11   11           State     TEXT        0       None   0
12   12     Postal Code  INTEGER        0       None   0
13   13          Region     TEXT        0       None   0
14   14      Product ID     TEXT        0       None   0
15   15        Category     TEXT        0       None   0
16   16    Sub-Category     TEXT        0       None   0
17   17    Product Name     TEXT        0       None   0
18   18           Sales     REAL        0       None   0
19   19        Quantity  INTEGER        0       None   0
20   20        Discount     REAL        0       None   0
21   21          Profit     REAL        0       None   0

# Step 2: Basic SQL Queries

### Objective

This section demonstrates the use of fundamental SQL statements to retrieve, filter, sort, and limit records from the Superstore dataset.

In [59]:
query = """
SELECT *
FROM superstore_data;
"""

pd.read_sql(query, conn)

,csvbase_row_id,﻿Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,3,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
2,5,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
3,6,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
4,7,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8822,9990,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
8823,9991,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
8824,9992,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
8825,9993,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
8826,9994,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [60]:
query = """
SELECT
    [Customer Name],
    Category,
    Sales,
    Profit
FROM superstore_data
LIMIT 10;
"""

pd.read_sql(query, conn)

     Customer Name         Category    Sales    Profit
0      Claire Gute        Furniture  261.960   41.9136
1  Darrin Van Huff  Office Supplies   14.620    6.8714
2   Sean O'Donnell  Office Supplies   22.368    2.5164
3  Brosina Hoffman        Furniture   48.860   14.1694
4  Brosina Hoffman  Office Supplies    7.280    1.9656
5  Brosina Hoffman  Office Supplies   18.504    5.7825
6  Brosina Hoffman  Office Supplies  114.900   34.4700
7     Andrew Allen  Office Supplies   15.552    5.4432
8     Irene Maddox  Office Supplies  407.976  132.5922
9    Harold Pawlan  Office Supplies   68.810 -123.8580

In [61]:
query = """
SELECT
    [Customer Name],
    Category,
    Sales,
    Profit
FROM superstore_data
WHERE Category = 'Furniture';
"""

pd.read_sql(query, conn)

         Customer Name   Category     Sales    Profit
0          Claire Gute  Furniture  261.9600   41.9136
1      Brosina Hoffman  Furniture   48.8600   14.1694
2      Sandra Flanagan  Furniture   71.3720   -1.0196
3      Tracy Blumstein  Furniture  124.2000   15.5250
4            Gene Hale  Furniture  190.9200 -147.9630
...                ...        ...       ...       ...
1649  Corinna Mitchell  Furniture  383.4656  -67.6704
1650      Harold Engle  Furniture   13.4000    6.4320
1651       Shaun Weien  Furniture   85.9800   22.3548
1652  Tom Boeckenhauer  Furniture   25.2480    4.1028
1653       Dave Brooks  Furniture   91.9600   15.6332

[1654 rows x 4 columns]

In [62]:
query = """
SELECT
    [Customer Name],
    Sales,
    Profit
FROM superstore_data
WHERE Sales > 400;
"""

pd.read_sql(query, conn)

       Customer Name    Sales    Profit
0       Irene Maddox  407.976  132.5922
1        Dave Brooks  457.568   51.4764
2     David Kendrick  408.744   76.6395
3    Laurel Elliston  444.768   44.4768
4    Victoria Wilson  452.450 -244.3230
..               ...      ...       ...
283       Dan Lawera  479.976  161.9919
284       Dan Lawera  483.136   60.3920
285    Sally Hughsby  403.560   96.8544
286        Liz Preis  466.320   34.9740
287       Anne Pryor  437.472  153.1152

[288 rows x 3 columns]

In [63]:
query = """
SELECT
    [Customer Name],
    Category,
    Sales
FROM superstore_data
ORDER BY Sales DESC;
"""

pd.read_sql(query, conn)

         Customer Name         Category    Sales
0      Cynthia Arntzen        Furniture  498.260
1         Tamara Chand       Technology  498.000
2        Justin Ritter  Office Supplies  497.940
3      Muhammed Yedwab  Office Supplies  497.610
4        Bruce Stewart  Office Supplies  496.860
...                ...              ...      ...
8822     Henry Goldwyn  Office Supplies    0.876
8823     Jas O'Carroll  Office Supplies    0.852
8824       Ken Brennan  Office Supplies    0.836
8825    Roland Schwarz  Office Supplies    0.556
8826  Zuschuss Carroll  Office Supplies    0.444

[8827 rows x 3 columns]

In [64]:
query = """
SELECT
    [Customer Name],
    [Product Name],
    Sales
FROM superstore_data
ORDER BY Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

,Customer Name,Product Name,Sales
0,Cynthia Arntzen,Harbour Creations 67200 Series Stacking Chairs,498.260
1,Tamara Chand,Enermax Acrylux Wireless Keyboard,498.000
2,Justin Ritter,GBC DocuBind P100 Manual Binding Machine,497.940
3,Muhammed Yedwab,Recycled Steel Personal File for Standard File...,497.610
4,Bruce Stewart,Sensible Storage WireTech Storage Systems,496.860
5,Carol Triggs,Mitel MiVoice 5330e IP Phone,494.982
6,Monica Federle,Ativa D5772 2-Line 5.8GHz Digital Expandable C...,494.970
7,Eudokia Martin,Ativa D5772 2-Line 5.8GHz Digital Expandable C...,494.970
8,Chloris Kastensmidt,GE 2-Jack Phone Line Splitter,494.376
9,Rob Dowd,Plantronics Voyager Pro Legend,494.376

In [65]:
query = """
SELECT
    [Customer Name],
    [Product Name],
    Profit
FROM superstore_data
ORDER BY Profit DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

,Customer Name,Product Name,Profit
0,Maurice Satty,"Dot Matrix Printer Tape Reel Labels, White, 50...",240.8595
1,Heather Kirkland,"Dot Matrix Printer Tape Reel Labels, White, 50...",240.8595
2,Christine Sundaresam,DYMO CardScan Personal V9 Business Card Scanner,239.9850
3,Gary Zandusky,Lexmark 20R1285 X6650 Wireless All-in-One Printer,225.6000
4,Justin Ritter,GBC DocuBind P100 Manual Binding Machine,224.0730
5,Frank Carlisle,Panasonic KX-TG9541B DECT 6.0 Digital 2-Line E...,220.4853
6,Ken Lonsdale,GBC Recycled Regency Composition Covers,219.9904
7,Daniel Raglin,Satellite Sectional Post Binders,219.6546
8,Brosina Hoffman,GBC ProClick Punch Binding System,219.4514
9,Frank Gastineau,GBC ProClick Punch Binding System,219.4514

## Conclusion

The following SQL statements were successfully used:

- SELECT
- WHERE
- ORDER BY
- LIMIT

These statements are essential for retrieving, filtering, sorting, and analyzing data efficiently.

# Step 3: Aggregate Functions, GROUP BY and HAVING

### Objective

This step demonstrates how SQL aggregate functions are used to summarize data and how `GROUP BY` and `HAVING` help analyze data by different categories.

In [66]:
query = """
SELECT
    SUM(Sales) AS Total_Sales
FROM superstore_data;
"""

pd.read_sql(query, conn)

   Total_Sales
0  819718.0554

In [67]:
query = """
SELECT
    AVG(Profit) AS Average_Profit
FROM superstore_data;
"""

pd.read_sql(query, conn)

   Average_Profit
0       11.198644

In [68]:
query = """
SELECT
    COUNT(*) AS Total_Orders
FROM superstore_data;
"""

pd.read_sql(query, conn)

   Total_Orders
0          8827

In [69]:
query = """
SELECT
    Category,
    SUM(Sales) AS Total_Sales
FROM superstore_data
GROUP BY Category;
"""

pd.read_sql(query, conn)

          Category  Total_Sales
0        Furniture  247877.6984
1  Office Supplies  343425.0040
2       Technology  228415.3530

In [70]:
query = """
SELECT
    Category,
    SUM(Profit) AS Total_Profit
FROM superstore_data
GROUP BY Category;
"""

pd.read_sql(query, conn)

          Category  Total_Profit
0        Furniture    -2714.5353
1  Office Supplies    66179.5379
2       Technology    35385.4240

In [71]:
query = """
SELECT
    Category,
    SUM(Sales) AS Total_Sales
FROM superstore_data
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

          Category  Total_Sales
0  Office Supplies  343425.0040
1        Furniture  247877.6984
2       Technology  228415.3530

In [72]:
query = """
SELECT
    Category,
    SUM(Sales) AS Total_Sales
FROM superstore_data
GROUP BY Category
HAVING SUM(Sales) > 500000;
"""

pd.read_sql(query, conn)

Empty DataFrame
Columns: [Category, Total_Sales]
Index: []

## Conclusion

The following SQL concepts were successfully implemented:

- SUM()
- AVG()
- COUNT()
- GROUP BY
- HAVING

These operations are commonly used in business reporting and dashboard creation to summarize and analyze data.

# Step 4: Advanced SQL

### Objective

In this step, advanced SQL concepts such as Subqueries, Common Table Expressions (CTEs), Window Functions, and Views are implemented to perform advanced data analysis.

In [73]:
query = """
SELECT
    "Customer Name",
    Sales
FROM superstore_data
WHERE Sales >
(
    SELECT AVG(Sales)
    FROM superstore_data
);
"""

pd.read_sql(query, conn)

           Customer Name    Sales
0            Claire Gute  261.960
1        Brosina Hoffman  114.900
2           Irene Maddox  407.976
3     Zuschuss Donatelli  213.480
4        Tracy Blumstein  124.200
...                  ...      ...
2753          Anne Pryor  437.472
2754          Ryan Crowe   97.980
2755        Ruben Ausman  206.100
2756         Dave Brooks  258.576
2757        Chris Cortes  243.160

[2758 rows x 2 columns]

In [74]:
query = """
WITH CategorySales AS
(
    SELECT
        Category,
        SUM(Sales) AS Total_Sales
    FROM superstore_data
    GROUP BY Category
)

SELECT *
FROM CategorySales;
"""

pd.read_sql(query, conn)

          Category  Total_Sales
0        Furniture  247877.6984
1  Office Supplies  343425.0040
2       Technology  228415.3530

In [75]:
query = """
SELECT
    "Customer Name",
    Category,
    Sales,
    ROW_NUMBER() OVER (ORDER BY Sales DESC) AS Row_Num
FROM superstore_data;
"""

pd.read_sql(query, conn)

         Customer Name         Category    Sales  Row_Num
0      Cynthia Arntzen        Furniture  498.260        1
1         Tamara Chand       Technology  498.000        2
2        Justin Ritter  Office Supplies  497.940        3
3      Muhammed Yedwab  Office Supplies  497.610        4
4        Bruce Stewart  Office Supplies  496.860        5
...                ...              ...      ...      ...
8822     Henry Goldwyn  Office Supplies    0.876     8823
8823     Jas O'Carroll  Office Supplies    0.852     8824
8824       Ken Brennan  Office Supplies    0.836     8825
8825    Roland Schwarz  Office Supplies    0.556     8826
8826  Zuschuss Carroll  Office Supplies    0.444     8827

[8827 rows x 4 columns]

In [76]:
query = """
SELECT
    "Customer Name",
    Sales,
    RANK() OVER (ORDER BY Sales DESC) AS Sales_Rank
FROM superstore_data;
"""

pd.read_sql(query, conn)

         Customer Name    Sales  Sales_Rank
0      Cynthia Arntzen  498.260           1
1         Tamara Chand  498.000           2
2        Justin Ritter  497.940           3
3      Muhammed Yedwab  497.610           4
4        Bruce Stewart  496.860           5
...                ...      ...         ...
8822     Henry Goldwyn    0.876        8823
8823     Jas O'Carroll    0.852        8824
8824       Ken Brennan    0.836        8825
8825    Roland Schwarz    0.556        8826
8826  Zuschuss Carroll    0.444        8827

[8827 rows x 3 columns]

In [77]:
query = """
SELECT
    "Order Date",
    Sales,
    LAG(Sales) OVER (ORDER BY "Order Date") AS Previous_Sales
FROM superstore_data;
"""

pd.read_sql(query, conn)

      Order Date    Sales  Previous_Sales
0     2014-01-03   16.448             NaN
1     2014-01-04   11.784          16.448
2     2014-01-04  272.736          11.784
3     2014-01-04    3.540         272.736
4     2014-01-05   19.536           3.540
...          ...      ...             ...
8822  2017-12-30   90.930         323.136
8823  2017-12-30   52.776          90.930
8824  2017-12-30   13.904          52.776
8825  2017-12-30   20.720          13.904
8826  2017-12-30    3.024          20.720

[8827 rows x 3 columns]

In [78]:
query = """
SELECT
    "Order Date",
    Sales,
    LEAD(Sales) OVER (ORDER BY "Order Date") AS Next_Sales
FROM superstore_data;
"""

pd.read_sql(query, conn)

      Order Date    Sales  Next_Sales
0     2014-01-03   16.448      11.784
1     2014-01-04   11.784     272.736
2     2014-01-04  272.736       3.540
3     2014-01-04    3.540      19.536
4     2014-01-05   19.536      19.440
...          ...      ...         ...
8822  2017-12-30   90.930      52.776
8823  2017-12-30   52.776      13.904
8824  2017-12-30   13.904      20.720
8825  2017-12-30   20.720       3.024
8826  2017-12-30    3.024         NaN

[8827 rows x 3 columns]

In [79]:
query = """
CREATE VIEW IF NOT EXISTS Category_Summary AS

SELECT
    Category,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit

FROM superstore_data

GROUP BY Category;
"""

conn.execute(query)

print("View Created Successfully!")

View Created Successfully!

In [80]:
query = """
SELECT *
FROM Category_Summary;
"""

pd.read_sql(query, conn)

          Category  Total_Sales  Total_Profit
0        Furniture  247877.6984    -2714.5353
1  Office Supplies  343425.0040    66179.5379
2       Technology  228415.3530    35385.4240

## Conclusion

The following advanced SQL concepts were successfully implemented:

- Subqueries
- Common Table Expressions (CTEs)
- ROW_NUMBER()
- RANK()
- LAG()
- LEAD()
- SQL Views

These techniques are widely used in business intelligence, reporting, and data analytics projects.

# Step 5: Business Insights using SQL

## Objective

In this step, SQL queries are executed to answer real-world business questions using the Superstore dataset.

In [95]:
import sqlite3
import pandas as pd

# Reconnect to the SQLite database
conn = sqlite3.connect("../database/superstore.db")

print("Database Connected Successfully!")

Database Connected Successfully!

## Question 1
What is the total sales generated by the company?

In [96]:
query = """
SELECT
SUM(Sales) AS Total_Sales
FROM superstore_data;
"""

pd.read_sql(query, conn)

   Total_Sales
0  819718.0554

## Question 2:
 What is the total profit earned by the company?

In [97]:
query = """
SELECT
SUM(Profit) AS Total_Profit
FROM superstore_data;
"""

pd.read_sql(query, conn)

   Total_Profit
0    98850.4266

## Question 3
 Which product category generates the highest sales?

In [98]:
query = """
SELECT
Category,
SUM(Sales) AS Total_Sales
FROM superstore_data
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

          Category  Total_Sales
0  Office Supplies  343425.0040
1        Furniture  247877.6984
2       Technology  228415.3530

## Question 4

 Which region contributes the highest sales?

In [99]:
query = """
SELECT
Region,
SUM(Sales) AS Total_Sales
FROM superstore_data
GROUP BY Region
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

    Region  Total_Sales
0     West  275810.2625
1     East  232887.4840
2  Central  183440.9134
3    South  127579.3955

## Question 5:
Who are the top 10 customers based on total sales?

In [100]:
query = """
SELECT
"Customer Name",
SUM(Sales) AS Total_Sales
FROM superstore_data
GROUP BY "Customer Name"
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

     Customer Name  Total_Sales
0       Paul Prost    4196.9280
1  Laura Armstrong    3751.7980
2     Ken Lonsdale    3371.6910
3         John Lee    3338.3520
4    William Brown    3131.9740
5     Noel Staavos    2964.8230
6      Rick Wilson    2879.8910
7    Sally Hughsby    2865.5995
8     Edward Hooks    2821.2100
9    Arthur Gainer    2806.8510

## Question 6

 Which are the top 10 best-selling products based on sales?

In [101]:
query = """
SELECT
"Product Name",
SUM(Sales) AS Total_Sales
FROM superstore_data
GROUP BY "Product Name"
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                                       Product Name  Total_Sales
0                        KI Adjustable-Height Table     4036.761
1   Global Wood Trimmed Manager's Task Chair, Khaki     3621.004
2        Situations Contoured Folding Chairs, 4/Set     2959.866
3         Global High-Back Leather Tilter, Burgundy     2841.069
4  Nortel Meridian M3904 Professional Digital phone     2802.618
5               Ibico Hi-Tech Manual Binding System     2653.413
6                 Fellowes Officeware Wire Shelving     2515.240
7                                 Easy-staple paper     2504.192
8                  Logitech Gaming G510s - Keyboard     2362.722
9     Space Solutions HD Industrial Steel Shelving.     2345.388

## Question 7
Which customer segment earns the highest profit?

In [102]:
query = """
SELECT
Segment,
SUM(Profit) AS Total_Profit
FROM superstore_data
GROUP BY Segment
ORDER BY Total_Profit DESC;
"""

pd.read_sql(query, conn)

       Segment  Total_Profit
0     Consumer    49390.0543
1    Corporate    28802.6274
2  Home Office    20657.7449

## Question 9
 Which are the top 5 states with the highest sales?

In [103]:
query = """
SELECT
State,
SUM(Sales) AS Total_Sales
FROM superstore_data
GROUP BY State
ORDER BY Total_Sales DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

          State  Total_Sales
0    California  175475.7375
1      New York   92379.4070
2         Texas   71672.9344
3  Pennsylvania   45628.6270
4    Washington   41245.3560

## Question 10
 What is the average discount provided for each product category?

In [104]:
query = """
SELECT
Category,
AVG(Discount) AS Average_Discount
FROM superstore_data
GROUP BY Category;
"""

pd.read_sql(query, conn)

          Category  Average_Discount
0        Furniture          0.176294
1  Office Supplies          0.159588
2       Technology          0.128404

In [105]:
conn.close()

print("Database Connection Closed Successfully!")

Database Connection Closed Successfully!

## Conclusion

Python was successfully integrated with SQLite to execute SQL queries and analyze the Superstore dataset.

Business insights such as sales, profit, customer performance, product performance, and regional analysis were generated using SQL.